### ISSUE TITLE
Bot randomly jumps voice channels.

### ISSUE THREAD

**Issue by Ovyerus** [awau/Clara#74] opened 2017-05-23 10:01 UTC
When the bot is supposed to leave a voice channel due to timeout or tries to reseed connections after a reboot, the bot sometimes randomly changes the channel it is in. Could be a lib issue or Discord issue as I cannot reliably recreate this.

**Comment by sr229** [comment] 2017-05-25 03:40
I think this is on the bot's code not on the library. We have several Eris bots not having this issue. We cannot tell though since we use the Git Snapshot of Eris.

**Comment by Ovyerus** [comment] 2017-12-29 07:06
Literally have only experienced on my testing bot, and no where else. Closing for now unless it's reported on one of the main bots.

**Comment by sr229** [comment] 2018-01-05 06:28
Persistent. Spotted on Nurse Riko

**Comment by sr229** [comment] 2018-01-05 06:48
Confirming it might be the Youtube Handler's fault and not adding a readiness check

**Comment by sr229** [comment] 2018-02-05 06:56
Confirmed to be caused by YouTube handler, setting to critical

**Comment by sr229** [comment] 2018-02-17 06:22
Fixed by library change.

**Closed as completed by sr229** 2018-02-17 06:22 UTC
Labels: bug, Critical
